package com.membership.card.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CARD".
 */
public class Card {

    private Long id;
    private String cardName;
    private String cardNumber;
    private String cardNumberType;
    private String cardBackground;

    public Card() {
    }

    public Card(Long id) {
        this.id = id;
    }

    public Card(Long id, String cardName, String cardNumber, String cardNumberType, String cardBackground) {
        this.id = id;
        this.cardName = cardName;
        this.cardNumber = cardNumber;
        this.cardNumberType = cardNumberType;
        this.cardBackground = cardBackground;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCardName() {
        return cardName;
    }

    public void setCardName(String cardName) {
        this.cardName = cardName;
    }

    public String getCardNumber() {
        return cardNumber;
    }

    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }

    public String getCardNumberType() {
        return cardNumberType;
    }

    public void setCardNumberType(String cardNumberType) {
        this.cardNumberType = cardNumberType;
    }

    public String getCardBackground() {
        return cardBackground;
    }

    public void setCardBackground(String cardBackground) {
        this.cardBackground = cardBackground;
    }

}
