package man.membership.com.membershipman;

/**
 * Created by HackerAnderson on 16. 9. 8..
 */
public class Demo {

    public static int[] covers = {R.drawable.card_cover_01, R.drawable.card_cover_02, R.drawable.card_cover_03, R.drawable.card_cover_04,
            R.drawable.card_cover_05, R.drawable.card_cover_06, R.drawable.card_cover_07, R.drawable.card_cover_08,
            R.drawable.card_cover_09,
            R.drawable.card_cover_10,
            R.drawable.card_cover_11,
            R.drawable.card_cover_12,
            R.drawable.card_cover_13,
            R.drawable.card_cover_14,
            R.drawable.card_cover_15,
            R.drawable.card_cover_16,
            R.drawable.card_cover_17,
            R.drawable.card_cover_18,
            R.drawable.card_cover_19,
            R.drawable.card_cover_20,
            R.drawable.card_cover_21,
            R.drawable.card_cover_22,
            R.drawable.card_cover_23,
            R.drawable.card_cover_24,
            R.drawable.card_cover_25,
            R.drawable.card_cover_26,
            R.drawable.card_cover_27,
            R.drawable.card_cover_28,
            R.drawable.card_cover_29,
            R.drawable.card_cover_30,
            R.drawable.card_cover_31,
            R.drawable.card_cover_32,
            R.drawable.card_cover_33,
            R.drawable.card_cover_34,
            R.drawable.card_cover_35,
            R.drawable.card_cover_36,
            R.drawable.card_cover_37,
            R.drawable.card_cover_38,
            R.drawable.card_cover_39,
            R.drawable.card_cover_40,
            R.drawable.card_cover_41,
            R.drawable.card_cover_42,
            R.drawable.card_cover_43,
            R.drawable.card_cover_44,
            R.drawable.card_cover_45,
            R.drawable.card_cover_46,
            R.drawable.card_cover_47,
            R.drawable.card_cover_48,
            R.drawable.card_cover_49,
            R.drawable.card_cover_50,
            R.drawable.card_cover_51,
            R.drawable.card_cover_52,
            R.drawable.card_cover_53,
            R.drawable.card_cover_54};

    public static int[] thumbCovers = {R.drawable.card_cover_01_thumb,
            R.drawable.card_cover_02_thumb,
            R.drawable.card_cover_03_thumb,
            R.drawable.card_cover_04_thumb,
            R.drawable.card_cover_05_thumb,
            R.drawable.card_cover_06_thumb,
            R.drawable.card_cover_07_thumb,
            R.drawable.card_cover_08_thumb,
            R.drawable.card_cover_09_thumb,
            R.drawable.card_cover_10_thumb,
            R.drawable.card_cover_11_thumb,
            R.drawable.card_cover_12_thumb,
            R.drawable.card_cover_13_thumb,
            R.drawable.card_cover_14_thumb,
            R.drawable.card_cover_15_thumb,
            R.drawable.card_cover_16_thumb,
            R.drawable.card_cover_17_thumb,
            R.drawable.card_cover_18_thumb,
            R.drawable.card_cover_19_thumb,
            R.drawable.card_cover_20_thumb,
            R.drawable.card_cover_21_thumb,
            R.drawable.card_cover_22_thumb,
            R.drawable.card_cover_23_thumb,
            R.drawable.card_cover_24_thumb,
            R.drawable.card_cover_25_thumb,
            R.drawable.card_cover_26_thumb,
            R.drawable.card_cover_27_thumb,
            R.drawable.card_cover_28_thumb,
            R.drawable.card_cover_29_thumb,
            R.drawable.card_cover_30_thumb,
            R.drawable.card_cover_31_thumb,
            R.drawable.card_cover_32_thumb,
            R.drawable.card_cover_33_thumb,
            R.drawable.card_cover_34_thumb,
            R.drawable.card_cover_35_thumb,
            R.drawable.card_cover_36_thumb,
            R.drawable.card_cover_37_thumb,
            R.drawable.card_cover_38_thumb,
            R.drawable.card_cover_39_thumb,
            R.drawable.card_cover_40_thumb,
            R.drawable.card_cover_41_thumb,
            R.drawable.card_cover_42_thumb,
            R.drawable.card_cover_43_thumb,
            R.drawable.card_cover_44_thumb,
            R.drawable.card_cover_45_thumb,
            R.drawable.card_cover_46_thumb,
            R.drawable.card_cover_47_thumb,
            R.drawable.card_cover_48_thumb,
            R.drawable.card_cover_49_thumb,
            R.drawable.card_cover_50_thumb,
            R.drawable.card_cover_51_thumb,
            R.drawable.card_cover_52_thumb,
            R.drawable.card_cover_53_thumb,
            R.drawable.card_cover_54_thumb};

    public static String[] name = {"아모레퍼시픽", "KT olleh", "LG uplus", "cj one", "korean air", "신세계백화점", "엘포인트", "롯데"};

    public static String[] barcode = {"124214", "124214", "3123", "1", "2", "4", "5", "1"};


}
